#### general settings
name: Predictorx4_setting1
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [0, 1, 2, 3]

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: DIV2K
    mode: GT
    dataroot_GT: /student/xmz/DCLS-SR-master/dataset/source/l.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 256
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: /student/xmz/DCLS-SR-master/dataset/HRblur_aniso_v/x4/l.lmdb
    dataroot_LQ: /student/xmz/DCLS-SR-master/dataset/LRblur_aniso_v/x4/l.lmdb

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr: !!float 2e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 90000
  warmup_iter: -1  # no warm up
  lr_steps: 100000
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 2e3

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2e3
